name: food
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  random_color: ^1.0.5 

  cupertino_icons: ^1.0.6
  intl: ^0.18.0
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  health: ^8.1.0
  flutter_stripe: ^11.0.0
  http: ^1.2.2
  provider: ^6.1.2
  image_picker: ^1.1.2
  cached_network_image: ^3.0.0
  path_provider: ^2.0.11
  share_plus: ^10.0.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.13.1

# flutter_launcher_icons:
#   android: 
#   image_path: "lib/images/app_logo.png"
#   ios: 
#     generate: true
#     image_path: "lib/images/app_logo.png"
#   macos: 
#     generate: true
#     image_path: "lib/images/app_logo.png"
  
flutter_launcher_icons:
  android: "launcher_icon"  
  ios: true
  image_path: "lib/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:    
    generate: true
    image_path: "lib/images/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"  
  windows:
    generate: true    
    image_path: "lib/images/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48  macos:
  macos: 
    generate: true    
    image_path: "lib/images/app_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - assets/images/no_profile_pic.png

  fonts: 
      - family: Poppins
        fonts: 
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-ExtraLightItalic.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-SemiBoldItalic.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf
